import internalModule from './modules/internalModule';
import styleGuideContainer from './modules/styleGuideContainer';
import personaGrid from './modules/personaGrid';
import tutorGrid from './modules/tutorGrid';
import mainLayout from './modules/mainLayout';
import footerTextCollapse from './modules/footerTextCollapse';
import secondaryMenu from './modules/secondaryMenu';
import midSizeSlider from './modules/midSizeSlider';
import smallSizeSlider from './modules/smallSizeSlider';
import singleSlider from './modules/singleSlider';
import smallSizeSliderBonuses from './modules/smallSizeSliderBonuses';
import smallSizeSliderStates from './modules/smallSizeSliderStates';
import sliderTopSportsbooks from './modules/sliderTopSportsbooks';
import accordion from './modules/accordion';
import topSports from './modules/topSports';
import initializeTabs from './modules/initializeTabs';
import initializeTabsProsCons from './modules/initializeTabsProsCons';
import dynamicSideBanner from './modules/dynamicSideBanner';
import matchupOddsBar from './modules/matchupOddsBar';
import categorySportsCards from './modules/categorySportsCards';
import oddsCompare from './modules/oddsCompare';
import ibdMap from './modules/ibdMap';
import graphqlPractice from './modules/graphqlPractice';
import subTabsSlider from './modules/subTabsSlider';
import Prism from 'prismjs';

const initComponents = () => {
	mainLayout();
	footerTextCollapse();
	secondaryMenu();
	midSizeSlider();
	smallSizeSlider();
	singleSlider();
	smallSizeSliderBonuses();
	smallSizeSliderStates();
	sliderTopSportsbooks();
	accordion();
	topSports();
	subTabsSlider();
	initializeTabs();
	initializeTabsProsCons();
	dynamicSideBanner();
	matchupOddsBar();
	categorySportsCards();
	oddsCompare();
	ibdMap();
	graphqlPractice();
	internalModule();
	styleGuideContainer();
	tutorGrid();
	personaGrid();
	Prism.highlightAll();
};

document.addEventListener('DOMContentLoaded', initComponents);
